# Numpy
**Aggregations :**
- sum
- min(axis = 1)
- max(axis = 0)
- median
- std


**Sorting Arrays :**
- sort
- sort(axis =0)

**Array Manipulation :**
- Transposing
- changing shape (ravel & reshape)
- adding/ removing elemnts
    - append
    - insert
    - delete
- Combining array
    - concatenate
    - hstack
    - vstack
    - ravel
    - flatten
    
**Saving & Loading files :**
- save('file_name', array)
- load('file_name.npy')


In [1]:
import numpy as np

In [6]:
n1 = np.array([1,2,3,4,5])
print("No. of dim.: " ,n1.ndim)
print("Size :", n1.size)
print("Shape : ", n1.shape)

No. of dim.:  1
Size : 5
Shape :  (5,)


In [7]:
n1.min()

1

In [8]:
n1.max()

5

In [26]:
n2 = np.array([[1,2,3],[4,5,2],[4,5,20],[90,89,78]])
n2.shape

(4, 3)

In [12]:
n2.min()

1

In [13]:
n2.max()

90

In [15]:
n2 # i want to know the min value of each columns
n2.min(axis = 0)

array([1, 2, 2])

In [16]:
n2.min(axis = 1) # for rows 

array([ 1,  2,  4, 78])

In [17]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  5, 20],
       [90, 89, 78]])

In [19]:
n2.mean(axis = 1)

array([ 2.        ,  3.66666667,  9.66666667, 85.66666667])

In [20]:
n2.mean(axis = 0)

array([24.75, 25.25, 25.75])

### Sorting Arrays :


sort

sort(axis =0)

In [24]:
np.sort(n2)

array([[ 1,  2,  3],
       [ 2,  4,  5],
       [ 4,  5, 20],
       [78, 89, 90]])

In [27]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  5, 20],
       [90, 89, 78]])

In [28]:
np.sort(n2, axis = 0)

array([[ 1,  2,  2],
       [ 4,  5,  3],
       [ 4,  5, 20],
       [90, 89, 78]])

In [30]:
np.sort(n2, axis = 1)

array([[ 1,  2,  3],
       [ 2,  4,  5],
       [ 4,  5, 20],
       [78, 89, 90]])

## Array Manipulation :

In [31]:
# Transposing
n2

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  5, 20],
       [90, 89, 78]])

In [32]:
np.transpose(n2)

array([[ 1,  4,  4, 90],
       [ 2,  5,  5, 89],
       [ 3,  2, 20, 78]])

In [33]:
n2.T

array([[ 1,  4,  4, 90],
       [ 2,  5,  5, 89],
       [ 3,  2, 20, 78]])

In [34]:
# changing shape 
np.ravel(n2) # multi- D to single - D

array([ 1,  2,  3,  4,  5,  2,  4,  5, 20, 90, 89, 78])

In [36]:
n2.flatten()

array([ 1,  2,  3,  4,  5,  2,  4,  5, 20, 90, 89, 78])

In [37]:
# reshape
# n2 shape is 4,3 = 12 - need to pass factors of 12
n2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  2],
       [ 4,  5, 20, 90, 89, 78]])

In [38]:
n2.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 2],
       [ 4],
       [ 5],
       [20],
       [90],
       [89],
       [78]])

In [44]:
n2.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  5, 20],
       [90, 89, 78]])

In [48]:
# adding/ removing elemnts
n3 = n2*5
np.add(n2,n3)

array([[  6,  12,  18],
       [ 24,  30,  12],
       [ 24,  30, 120],
       [540, 534, 468]])

In [55]:
n2[:1,:1] = 100

In [56]:
n2

array([[100,   2,   3],
       [  4,   5,   2],
       [  4,   5,  20],
       [ 90,  89,  78]])

In [61]:
n2[1:2, 1:2] = -1
n2

array([[100,   2,   3],
       [  4,  -1,   2],
       [  4,   5,  20],
       [ 90,  89,  78]])

In [62]:
# append
np.append(n2,n3)

array([100,   2,   3,   4,  -1,   2,   4,   5,  20,  90,  89,  78,   5,
        10,  15,  20,  25,  10,  20,  25, 100, 450, 445, 390])

In [63]:
np.append(n3,n2)

array([  5,  10,  15,  20,  25,  10,  20,  25, 100, 450, 445, 390, 100,
         2,   3,   4,  -1,   2,   4,   5,  20,  90,  89,  78])

In [65]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [68]:
np.insert(n2, -1, 1000)

array([ 100,    2,    3,    4,   -1,    2,    4,    5,   20,   90,   89,
       1000,   78])

In [73]:
len(n2)
n2.size

12

In [76]:
np.insert(n2, 2, -2) # array, object(position), value/data

array([100,   2,  -2,   3,   4,  -1,   2,   4,   5,  20,  90,  89,  78])

In [77]:
np.insert(n2, 2, -2).size

13

In [80]:
np.delete(n2, 0 ) # array, index values 

array([ 2,  3,  4, -1,  2,  4,  5, 20, 90, 89, 78])

In [82]:
np.append(n2,n3, axis = 0)

array([[100,   2,   3],
       [  4,  -1,   2],
       [  4,   5,  20],
       [ 90,  89,  78],
       [  5,  10,  15],
       [ 20,  25,  10],
       [ 20,  25, 100],
       [450, 445, 390]])

In [83]:
np.append(n2,n3, axis = 1)

array([[100,   2,   3,   5,  10,  15],
       [  4,  -1,   2,  20,  25,  10],
       [  4,   5,  20,  20,  25, 100],
       [ 90,  89,  78, 450, 445, 390]])

In [92]:
np.concatenate(n2 , axis = 0)

array([100,   2,   3,   4,  -1,   2,   4,   5,  20,  90,  89,  78])

In [86]:
n2

array([[100,   2,   3],
       [  4,  -1,   2],
       [  4,   5,  20],
       [ 90,  89,  78]])

In [96]:
b = np.hstack(n3)
b

array([  5,  10,  15,  20,  25,  10,  20,  25, 100, 450, 445, 390])

In [94]:
n3

array([[  5,  10,  15],
       [ 20,  25,  10],
       [ 20,  25, 100],
       [450, 445, 390]])

In [97]:
np.vstack(b)

array([[  5],
       [ 10],
       [ 15],
       [ 20],
       [ 25],
       [ 10],
       [ 20],
       [ 25],
       [100],
       [450],
       [445],
       [390]])

In [98]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [109]:
n = np.linspace(10,100,30)
n.sort()
result  = n.reshape(2,-1)
result

array([[ 10.        ,  13.10344828,  16.20689655,  19.31034483,
         22.4137931 ,  25.51724138,  28.62068966,  31.72413793,
         34.82758621,  37.93103448,  41.03448276,  44.13793103,
         47.24137931,  50.34482759,  53.44827586],
       [ 56.55172414,  59.65517241,  62.75862069,  65.86206897,
         68.96551724,  72.06896552,  75.17241379,  78.27586207,
         81.37931034,  84.48275862,  87.5862069 ,  90.68965517,
         93.79310345,  96.89655172, 100.        ]])

## Saving & Loading files :

save('file_name', array)
load('file_name.npy')

In [110]:
np.save("Sample", result) # exporting

In [113]:
# %load ("Sample.npy")
np.load("Sample.npy") # reading numpy array

array([[ 10.        ,  13.10344828,  16.20689655,  19.31034483,
         22.4137931 ,  25.51724138,  28.62068966,  31.72413793,
         34.82758621,  37.93103448,  41.03448276,  44.13793103,
         47.24137931,  50.34482759,  53.44827586],
       [ 56.55172414,  59.65517241,  62.75862069,  65.86206897,
         68.96551724,  72.06896552,  75.17241379,  78.27586207,
         81.37931034,  84.48275862,  87.5862069 ,  90.68965517,
         93.79310345,  96.89655172, 100.        ]])

In [115]:
del result

In [116]:
result

NameError: name 'result' is not defined

# Task 

write a program to create below nd-Array

7 7 7 7 7

7 7 0 7 7

7 7 7 7 7

# Pandas

In [117]:
import pandas 

In [118]:
import pandas as pd

## Pandas Series

In [120]:
# creating pandas series using list
li = [12,23,34,45,56,67]
s1 = pd.Series(li)
s1

0    12
1    23
2    34
3    45
4    56
5    67
dtype: int64

In [121]:
np.array(li)

array([12, 23, 34, 45, 56, 67])

In [123]:
s2 = pd.Series((1,2,"str"))
s2

0      1
1      2
2    str
dtype: object

In [126]:
di = {"name" : "Divya", "pin" : 432, "Gender" : "F"
}
s3 = pd.Series(di)
s3

name      Divya
pin         432
Gender        F
dtype: object

In [129]:
n = np.arange(10,100,10)
n

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [130]:
s4 = pd.Series(n)
s4

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int32

In [131]:
s4.shape

(9,)

In [133]:
len(dir(pd.Series))

433

In [135]:
len(dir(pd))

142

In [136]:
pd.date_range(start = "2021-09-13", end = "2021-10-02")

DatetimeIndex(['2021-09-13', '2021-09-14', '2021-09-15', '2021-09-16',
               '2021-09-17', '2021-09-18', '2021-09-19', '2021-09-20',
               '2021-09-21', '2021-09-22', '2021-09-23', '2021-09-24',
               '2021-09-25', '2021-09-26', '2021-09-27', '2021-09-28',
               '2021-09-29', '2021-09-30', '2021-10-01', '2021-10-02'],
              dtype='datetime64[ns]', freq='D')

In [137]:
# re indexing
s4

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int32

In [138]:
s4.index

RangeIndex(start=0, stop=9, step=1)

In [139]:
s4.values

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [141]:
s4.index = [2,3,'e',2,2,"s",0,'f', 34.3]
s4

2       10
3       20
e       30
2       40
2       50
s       60
0       70
f       80
34.3    90
dtype: int32

# Slicing and Indexing

In [142]:
s4[2]

2    10
2    40
2    50
dtype: int32

In [144]:
s4[5]

KeyError: 5

In [145]:
s4["e"]

30

In [149]:
s3

name      Divya
pin         432
Gender        F
dtype: object

In [150]:
s3["pin"]

432

In [151]:
s3["Gender"]

'F'

In [154]:
s5 = pd.Series(np.arange(10))
s5[::2]

0    0
2    2
4    4
6    6
8    8
dtype: int32

In [155]:
s5[1::2]

1    1
3    3
5    5
7    7
9    9
dtype: int32

# Task
- write a program to create a series having 20 to 35 index, values are squares of index values 

- 20 400
- 21 441
- 22 484

In [159]:
22**2

484